version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "nmeierpolys"
    assignees:
      - "nmeierpolys"
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      dev-dependencies:
        patterns:
          - "@types/*"
          - "@typescript-eslint/*"
          - "eslint*"
          - "typescript"
          - "vitest*"
          - "@vitest/*"
          - "vite"
        update-types:
          - "minor"
          - "patch"
      production-dependencies:
        patterns:
          - "@modelcontextprotocol/*"
          - "chokidar"
          - "gray-matter"
        update-types:
          - "minor"
          - "patch"